# Generated by Django 4.1.7 on 2023-02-27 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("board_idx", models.IntegerField()),
                ("writer", models.CharField(max_length=50)),
                ("content", models.TextField()),
                (
                    "content_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="board",
            name="down",
            field=models.IntegerField(default=0),
        ),
    ]
