# Generated by Django 4.1.7 on 2023-02-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp01", "0002_comment_alter_board_down"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content_date",
            new_name="post_date",
        ),
    ]
