# Generated by Django 4.1.7 on 2023-03-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp03", "0002_alter_board_writer_alter_comment_writer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=500)),
                ("tmef", models.TextField(null=True)),
                ("wf", models.TextField(null=True)),
                ("tmn", models.IntegerField(default=0)),
                ("tmx", models.IntegerField(default=0)),
            ],
        ),
    ]
