# Generated by Django 4.1.7 on 2023-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp03", "0003_forecast"),
    ]

    operations = [
        migrations.CreateModel(
            name="melon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=500)),
                ("singer", models.CharField(max_length=500)),
                ("album", models.CharField(max_length=500)),
            ],
        ),
    ]
